
package service.admin;

import dto.AppointmentType;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Admin", targetNamespace = "http://endpoint/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Admin {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAppointmentAvailability", targetNamespace = "http://endpoint/", className = "service.admin.ListAppointmentAvailability")
    @ResponseWrapper(localName = "listAppointmentAvailabilityResponse", targetNamespace = "http://endpoint/", className = "service.admin.ListAppointmentAvailabilityResponse")
    @Action(input = "http://endpoint/Admin/listAppointmentAvailabilityRequest", output = "http://endpoint/Admin/listAppointmentAvailabilityResponse")
    public String listAppointmentAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
            AppointmentType arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listLocalAppointmentAvailability", targetNamespace = "http://endpoint/", className = "service.admin.ListLocalAppointmentAvailability")
    @ResponseWrapper(localName = "listLocalAppointmentAvailabilityResponse", targetNamespace = "http://endpoint/", className = "service.admin.ListLocalAppointmentAvailabilityResponse")
    @Action(input = "http://endpoint/Admin/listLocalAppointmentAvailabilityRequest", output = "http://endpoint/Admin/listLocalAppointmentAvailabilityResponse")
    public String listLocalAppointmentAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
        AppointmentType arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAppointment", targetNamespace = "http://endpoint/", className = "service.admin.AddAppointment")
    @ResponseWrapper(localName = "addAppointmentResponse", targetNamespace = "http://endpoint/", className = "service.admin.AddAppointmentResponse")
    @Action(input = "http://endpoint/Admin/addAppointmentRequest", output = "http://endpoint/Admin/addAppointmentResponse")
    public boolean addAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        AppointmentType arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeAppointment", targetNamespace = "http://endpoint/", className = "service.admin.RemoveAppointment")
    @ResponseWrapper(localName = "removeAppointmentResponse", targetNamespace = "http://endpoint/", className = "service.admin.RemoveAppointmentResponse")
    @Action(input = "http://endpoint/Admin/removeAppointmentRequest", output = "http://endpoint/Admin/removeAppointmentResponse")
    public String removeAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        AppointmentType arg1);

}
