
package service.admin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminImplService", targetNamespace = "http://impl/", wsdlLocation = "http://localhost:8080/adminservice?wsdl")
public class AdminImplService
    extends Service
{

    private final static URL ADMINIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINIMPLSERVICE_EXCEPTION;
    private final static QName ADMINIMPLSERVICE_QNAME = new QName("http://impl/", "AdminImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/adminservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINIMPLSERVICE_WSDL_LOCATION = url;
        ADMINIMPLSERVICE_EXCEPTION = e;
    }

    public AdminImplService() {
        super(__getWsdlLocation(), ADMINIMPLSERVICE_QNAME);
    }

    public AdminImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINIMPLSERVICE_QNAME, features);
    }

    public AdminImplService(URL wsdlLocation) {
        super(wsdlLocation, ADMINIMPLSERVICE_QNAME);
    }

    public AdminImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINIMPLSERVICE_QNAME, features);
    }

    public AdminImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Admin
     */
    @WebEndpoint(name = "AdminImplPort")
    public Admin getAdminImplPort() {
        return super.getPort(new QName("http://impl/", "AdminImplPort"), Admin.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Admin
     */
    @WebEndpoint(name = "AdminImplPort")
    public Admin getAdminImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl/", "AdminImplPort"), Admin.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINIMPLSERVICE_EXCEPTION!= null) {
            throw ADMINIMPLSERVICE_EXCEPTION;
        }
        return ADMINIMPLSERVICE_WSDL_LOCATION;
    }

}
