
package service.patient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PatientImplService", targetNamespace = "http://impl/", wsdlLocation = "http://localhost:8080/patientservice?wsdl")
public class PatientImplService
    extends Service
{

    private final static URL PATIENTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PATIENTIMPLSERVICE_EXCEPTION;
    private final static QName PATIENTIMPLSERVICE_QNAME = new QName("http://impl/", "PatientImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/patientservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PATIENTIMPLSERVICE_WSDL_LOCATION = url;
        PATIENTIMPLSERVICE_EXCEPTION = e;
    }

    public PatientImplService() {
        super(__getWsdlLocation(), PATIENTIMPLSERVICE_QNAME);
    }

    public PatientImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PATIENTIMPLSERVICE_QNAME, features);
    }

    public PatientImplService(URL wsdlLocation) {
        super(wsdlLocation, PATIENTIMPLSERVICE_QNAME);
    }

    public PatientImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PATIENTIMPLSERVICE_QNAME, features);
    }

    public PatientImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PatientImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Patient
     */
    @WebEndpoint(name = "PatientImplPort")
    public Patient getPatientImplPort() {
        return super.getPort(new QName("http://impl/", "PatientImplPort"), Patient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Patient
     */
    @WebEndpoint(name = "PatientImplPort")
    public Patient getPatientImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl/", "PatientImplPort"), Patient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PATIENTIMPLSERVICE_EXCEPTION!= null) {
            throw PATIENTIMPLSERVICE_EXCEPTION;
        }
        return PATIENTIMPLSERVICE_WSDL_LOCATION;
    }

}
